{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: blitz-migrate
    kubepivot.io/name: {{ .Chart.Name }}
    kubepivot.io/instance: {{ .Release.Name }}
spec:
  backoffLimit: {{ .Values.migrate.backoffLimit }}
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-postgres
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z blitz-postgres 5432; do sleep 2; done']
      containers:
        - name: migrate
          image: "{{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.migrate.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: blitz-secret
                  key: DATABASE_URL
{{- end }}
