version: '3.8'

services:
  bitcoind:
    image: qingchun22/bitcoind-regtest:latest
    container_name: bitcoind
    restart: always
    ports:
      - "18443:18443"
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin
    healthcheck:
      test: [ "CMD", "bitcoin-cli", "-regtest", "-rpcuser=user", "-rpcpassword=pass", "getblockchaininfo" ]
      interval: 10s
      timeout: 5s
      retries: 5

  geth:
    image: ethereum/client-go:latest
    container_name: geth
    restart: always
    command:
      - --dev
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,personal,miner
      - --dev.period=5
    ports:
      - "8545:8545"

  wallet-service:
    build:
      context: .
      dockerfile: build/docker/wallet-service/Dockerfile
    container_name: wallet-service
    restart: always
    depends_on:
      bitcoind:
        condition: service_healthy
      geth:
        condition: service_started
    ports:
      - "2113:2113"
    environment:
      - WALLET_HD_SEED=${WALLET_HD_SEED}
    volumes:
      - wallet-data:/app/data

volumes:
  bitcoind-data:
  wallet-data:


environment:
  - WALLET_HD_SEED=${WALLET_HD_SEED}
  - BTC_RPC_HOST=bitcoind:18443/wallet/blitz_wallet
  - ETH_RPC_HOST=http://geth:8545
