services:
  bitcoind:
    image: qingchun22/bitcoind-regtest:latest
    container_name: bitcoind
    restart: always
    user: root
    ports:
      - "18443:18443"
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin
    healthcheck:
      test: [ "CMD", "bitcoin-cli", "-regtest", "-rpcuser=user", "-rpcpassword=pass", "getblockchaininfo" ]
      interval: 10s
      timeout: 5s
      retries: 5

  geth:
    image: ethereum/client-go:latest
    container_name: geth
    restart: always
    command:
      - --dev
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,personal,miner
      - --dev.period=5
    ports:
      - "8545:8545"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: blitz
      POSTGRES_PASSWORD: blitz
      POSTGRES_DB: blitz
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U blitz -d blitz" ]
      interval: 5s
      timeout: 3s
      retries: 5

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    command:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2379:2379"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  wallet-service:
    build:
      context: .
      dockerfile: build/docker/wallet-service/Dockerfile
    container_name: wallet-service
    restart: always
    depends_on:
      bitcoind:
        condition: service_healthy
      geth:
        condition: service_started
      postgres:
        condition: service_healthy
      etcd:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "2113:2113"
    environment:
      - WALLET_HD_SEED=${WALLET_HD_SEED}
      - BTC_RPC_HOST=bitcoind:18443/wallet/blitz_wallet
      - ETH_RPC_HOST=http://geth:8545
      - DATABASE_URL=postgres://blitz:blitz@postgres:5432/blitz?sslmode=disable
      - ETCD_ENDPOINTS=etcd:2379
      - REDIS_URL=redis://redis:6379
    volumes:
      - wallet-data:/app/data

volumes:
  bitcoind-data:
  postgres-data:
  wallet-data: