resources:
  - kind: Deployment
    name: wallet-service
    namespace: web3-blitz
    on-missing: auto-heal
    max_retry: 3
    fallback: rollback

  - kind: StatefulSet
    name: postgres
    namespace: web3-blitz
    on-missing: alert
    max_retry: 0
    fallback: ""