apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-reconcile
  namespace: {{ .Release.Namespace }}
  labels:
    app: blitz-reconcile
    kubepivot.io/name: {{ .Chart.Name }}
    kubepivot.io/instance: {{ .Release.Name }}
