// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Deposit struct {
	ID        int64        `db:"id" json:"id"`
	TxID      string       `db:"tx_id" json:"tx_id"`
	Address   string       `db:"address" json:"address"`
	UserID    string       `db:"user_id" json:"user_id"`
	Amount    string       `db:"amount" json:"amount"`
	Height    int64        `db:"height" json:"height"`
	Confirmed int32        `db:"confirmed" json:"confirmed"`
	Chain     string       `db:"chain" json:"chain"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type DepositAddress struct {
	ID        int64        `db:"id" json:"id"`
	UserID    string       `db:"user_id" json:"user_id"`
	Address   string       `db:"address" json:"address"`
	Chain     string       `db:"chain" json:"chain"`
	Path      string       `db:"path" json:"path"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int64        `db:"id" json:"id"`
	Username  string       `db:"username" json:"username"`
	Password  string       `db:"password" json:"password"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type Withdrawal struct {
	ID        int64          `db:"id" json:"id"`
	TxID      sql.NullString `db:"tx_id" json:"tx_id"`
	Address   string         `db:"address" json:"address"`
	UserID    string         `db:"user_id" json:"user_id"`
	Amount    string         `db:"amount" json:"amount"`
	Fee       string         `db:"fee" json:"fee"`
	Status    string         `db:"status" json:"status"`
	Chain     string         `db:"chain" json:"chain"`
	CreatedAt sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at" json:"updated_at"`
}
