// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type DeadLetter struct {
	ID        int64           `db:"id" json:"id"`
	Type      string          `db:"type" json:"type"`
	Payload   json.RawMessage `db:"payload" json:"payload"`
	Error     string          `db:"error" json:"error"`
	Retries   int32           `db:"retries" json:"retries"`
	Resolved  bool            `db:"resolved" json:"resolved"`
	CreatedAt sql.NullTime    `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime    `db:"updated_at" json:"updated_at"`
}

type Deposit struct {
	ID        int64        `db:"id" json:"id"`
	TxID      string       `db:"tx_id" json:"tx_id"`
	Address   string       `db:"address" json:"address"`
	UserID    string       `db:"user_id" json:"user_id"`
	Amount    string       `db:"amount" json:"amount"`
	Height    int64        `db:"height" json:"height"`
	Confirmed int32        `db:"confirmed" json:"confirmed"`
	Chain     string       `db:"chain" json:"chain"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type DepositAddress struct {
	ID        int64        `db:"id" json:"id"`
	UserID    string       `db:"user_id" json:"user_id"`
	Address   string       `db:"address" json:"address"`
	Chain     string       `db:"chain" json:"chain"`
	Path      string       `db:"path" json:"path"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type Permission struct {
	ID          int64        `db:"id" json:"id"`
	Name        string       `db:"name" json:"name"`
	Description string       `db:"description" json:"description"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID        int64        `db:"id" json:"id"`
	UserID    int64        `db:"user_id" json:"user_id"`
	Token     string       `db:"token" json:"token"`
	ExpiresAt time.Time    `db:"expires_at" json:"expires_at"`
	Revoked   bool         `db:"revoked" json:"revoked"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type Role struct {
	ID          int64        `db:"id" json:"id"`
	Name        string       `db:"name" json:"name"`
	Description string       `db:"description" json:"description"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
}

type RolePermission struct {
	RoleID       int64 `db:"role_id" json:"role_id"`
	PermissionID int64 `db:"permission_id" json:"permission_id"`
}

type User struct {
	ID        int64        `db:"id" json:"id"`
	Level     int32        `db:"level" json:"level"`
	Username  string       `db:"username" json:"username"`
	Password  string       `db:"password" json:"password"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type UserRole struct {
	UserID int64 `db:"user_id" json:"user_id"`
	RoleID int64 `db:"role_id" json:"role_id"`
}

type Withdrawal struct {
	ID        int64          `db:"id" json:"id"`
	TxID      sql.NullString `db:"tx_id" json:"tx_id"`
	Address   string         `db:"address" json:"address"`
	UserID    string         `db:"user_id" json:"user_id"`
	Amount    string         `db:"amount" json:"amount"`
	Fee       string         `db:"fee" json:"fee"`
	Status    string         `db:"status" json:"status"`
	Chain     string         `db:"chain" json:"chain"`
	CreatedAt sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type WithdrawalLimit struct {
	ID         int64        `db:"id" json:"id"`
	Level      int32        `db:"level" json:"level"`
	LevelName  string       `db:"level_name" json:"level_name"`
	BtcDaily   string       `db:"btc_daily" json:"btc_daily"`
	EthDaily   string       `db:"eth_daily" json:"eth_daily"`
	MinDeposit string       `db:"min_deposit" json:"min_deposit"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
}
