// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createDeposit = `-- name: CreateDeposit :exec
INSERT INTO deposits (tx_id, address, user_id, amount, height, confirmed, chain)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDepositParams struct {
	TxID      string `db:"tx_id" json:"tx_id"`
	Address   string `db:"address" json:"address"`
	UserID    string `db:"user_id" json:"user_id"`
	Amount    string `db:"amount" json:"amount"`
	Height    int64  `db:"height" json:"height"`
	Confirmed int32  `db:"confirmed" json:"confirmed"`
	Chain     string `db:"chain" json:"chain"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) error {
	_, err := q.db.ExecContext(ctx, createDeposit,
		arg.TxID,
		arg.Address,
		arg.UserID,
		arg.Amount,
		arg.Height,
		arg.Confirmed,
		arg.Chain,
	)
	return err
}

const createDepositAddress = `-- name: CreateDepositAddress :exec
INSERT INTO deposit_addresses (user_id, address, chain, path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (address) DO NOTHING
`

type CreateDepositAddressParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	Address string `db:"address" json:"address"`
	Chain   string `db:"chain" json:"chain"`
	Path    string `db:"path" json:"path"`
}

func (q *Queries) CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) error {
	_, err := q.db.ExecContext(ctx, createDepositAddress,
		arg.UserID,
		arg.Address,
		arg.Chain,
		arg.Path,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING id, username, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (address, user_id, amount, fee, status, chain)
VALUES ($1, $2, $3, 0, 'pending', $4)
RETURNING id, tx_id, address, user_id, amount, fee, status, chain, created_at, updated_at
`

type CreateWithdrawalParams struct {
	Address string `db:"address" json:"address"`
	UserID  string `db:"user_id" json:"user_id"`
	Amount  string `db:"amount" json:"amount"`
	Chain   string `db:"chain" json:"chain"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRowContext(ctx, createWithdrawal,
		arg.Address,
		arg.UserID,
		arg.Amount,
		arg.Chain,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Address,
		&i.UserID,
		&i.Amount,
		&i.Fee,
		&i.Status,
		&i.Chain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByAddress = `-- name: GetAddressByAddress :one
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses WHERE address = $1 LIMIT 1
`

func (q *Queries) GetAddressByAddress(ctx context.Context, address string) (DepositAddress, error) {
	row := q.db.QueryRowContext(ctx, getAddressByAddress, address)
	var i DepositAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Chain,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getAllChainsTotalDeposit = `-- name: GetAllChainsTotalDeposit :one
SELECT COALESCE(SUM(amount), 0) as total
FROM deposits
WHERE confirmed = 1
`

func (q *Queries) GetAllChainsTotalDeposit(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAllChainsTotalDeposit)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getDepositByTxID = `-- name: GetDepositByTxID :one
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE tx_id = $1 LIMIT 1
`

func (q *Queries) GetDepositByTxID(ctx context.Context, txID string) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByTxID, txID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Address,
		&i.UserID,
		&i.Amount,
		&i.Height,
		&i.Confirmed,
		&i.Chain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalDepositByChain = `-- name: GetTotalDepositByChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM deposits
WHERE chain = $1 AND confirmed = 1
`

func (q *Queries) GetTotalDepositByChain(ctx context.Context, chain string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalDepositByChain, chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalDepositByUserIDAndChain = `-- name: GetTotalDepositByUserIDAndChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM deposits
WHERE user_id = $1 AND chain = $2 AND confirmed = 1
`

type GetTotalDepositByUserIDAndChainParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Chain  string `db:"chain" json:"chain"`
}

func (q *Queries) GetTotalDepositByUserIDAndChain(ctx context.Context, arg GetTotalDepositByUserIDAndChainParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalDepositByUserIDAndChain, arg.UserID, arg.Chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalWithdrawalByUserIDAndChain = `-- name: GetTotalWithdrawalByUserIDAndChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM withdrawals
WHERE user_id = $1 AND chain = $2 AND status = 'completed'
`

type GetTotalWithdrawalByUserIDAndChainParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Chain  string `db:"chain" json:"chain"`
}

func (q *Queries) GetTotalWithdrawalByUserIDAndChain(ctx context.Context, arg GetTotalWithdrawalByUserIDAndChainParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalWithdrawalByUserIDAndChain, arg.UserID, arg.Chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesByUserID = `-- name: ListAddressesByUserID :many
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAddressesByUserID(ctx context.Context, userID string) ([]DepositAddress, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Chain,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDepositAddresses = `-- name: ListAllDepositAddresses :many
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses ORDER BY created_at ASC
`

func (q *Queries) ListAllDepositAddresses(ctx context.Context) ([]DepositAddress, error) {
	rows, err := q.db.QueryContext(ctx, listAllDepositAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Chain,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByChain = `-- name: ListDepositsByChain :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE chain = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByChain(ctx context.Context, chain string) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDepositsByChain, chain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByUserID = `-- name: ListDepositsByUserID :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByUserID(ctx context.Context, userID string) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDepositsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedDeposits = `-- name: ListUnconfirmedDeposits :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits
WHERE confirmed = 0
ORDER BY height ASC
`

func (q *Queries) ListUnconfirmedDeposits(ctx context.Context) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listUnconfirmedDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByUserID = `-- name: ListWithdrawalsByUserID :many
SELECT id, tx_id, address, user_id, amount, fee, status, chain, created_at, updated_at FROM withdrawals WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWithdrawalsByUserID(ctx context.Context, userID string) ([]Withdrawal, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Fee,
			&i.Status,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepositConfirmed = `-- name: UpdateDepositConfirmed :exec
UPDATE deposits
SET confirmed = 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDepositConfirmed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDepositConfirmed, id)
	return err
}

const updateWithdrawalTx = `-- name: UpdateWithdrawalTx :exec
UPDATE withdrawals
SET tx_id = $1, fee = $2, status = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateWithdrawalTxParams struct {
	TxID   sql.NullString `db:"tx_id" json:"tx_id"`
	Fee    string         `db:"fee" json:"fee"`
	Status string         `db:"status" json:"status"`
	ID     int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateWithdrawalTx(ctx context.Context, arg UpdateWithdrawalTxParams) error {
	_, err := q.db.ExecContext(ctx, updateWithdrawalTx,
		arg.TxID,
		arg.Fee,
		arg.Status,
		arg.ID,
	)
	return err
}
