// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	RoleID int64 `db:"role_id" json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const createDeadLetter = `-- name: CreateDeadLetter :exec
INSERT INTO dead_letters (type, payload, error, retries)
VALUES ($1, $2, $3, $4)
`

type CreateDeadLetterParams struct {
	Type    string          `db:"type" json:"type"`
	Payload json.RawMessage `db:"payload" json:"payload"`
	Error   string          `db:"error" json:"error"`
	Retries int32           `db:"retries" json:"retries"`
}

func (q *Queries) CreateDeadLetter(ctx context.Context, arg CreateDeadLetterParams) error {
	_, err := q.db.ExecContext(ctx, createDeadLetter,
		arg.Type,
		arg.Payload,
		arg.Error,
		arg.Retries,
	)
	return err
}

const createDeposit = `-- name: CreateDeposit :exec
INSERT INTO deposits (tx_id, address, user_id, amount, height, confirmed, chain)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDepositParams struct {
	TxID      string `db:"tx_id" json:"tx_id"`
	Address   string `db:"address" json:"address"`
	UserID    string `db:"user_id" json:"user_id"`
	Amount    string `db:"amount" json:"amount"`
	Height    int64  `db:"height" json:"height"`
	Confirmed int32  `db:"confirmed" json:"confirmed"`
	Chain     string `db:"chain" json:"chain"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) error {
	_, err := q.db.ExecContext(ctx, createDeposit,
		arg.TxID,
		arg.Address,
		arg.UserID,
		arg.Amount,
		arg.Height,
		arg.Confirmed,
		arg.Chain,
	)
	return err
}

const createDepositAddress = `-- name: CreateDepositAddress :exec
INSERT INTO deposit_addresses (user_id, address, chain, path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (address) DO NOTHING
`

type CreateDepositAddressParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	Address string `db:"address" json:"address"`
	Chain   string `db:"chain" json:"chain"`
	Path    string `db:"path" json:"path"`
}

func (q *Queries) CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) error {
	_, err := q.db.ExecContext(ctx, createDepositAddress,
		arg.UserID,
		arg.Address,
		arg.Chain,
		arg.Path,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64     `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING id, level, username, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (address, user_id, amount, fee, status, chain)
VALUES ($1, $2, $3, 0, 'pending', $4)
RETURNING id, tx_id, address, user_id, amount, fee, status, chain, created_at, updated_at
`

type CreateWithdrawalParams struct {
	Address string `db:"address" json:"address"`
	UserID  string `db:"user_id" json:"user_id"`
	Amount  string `db:"amount" json:"amount"`
	Chain   string `db:"chain" json:"chain"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRowContext(ctx, createWithdrawal,
		arg.Address,
		arg.UserID,
		arg.Amount,
		arg.Chain,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Address,
		&i.UserID,
		&i.Amount,
		&i.Fee,
		&i.Status,
		&i.Chain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByAddress = `-- name: GetAddressByAddress :one
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses WHERE address = $1 LIMIT 1
`

func (q *Queries) GetAddressByAddress(ctx context.Context, address string) (DepositAddress, error) {
	row := q.db.QueryRowContext(ctx, getAddressByAddress, address)
	var i DepositAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Chain,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getAllChainsTotalDeposit = `-- name: GetAllChainsTotalDeposit :one
SELECT COALESCE(SUM(amount), 0) as total
FROM deposits
WHERE confirmed = 1
`

func (q *Queries) GetAllChainsTotalDeposit(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAllChainsTotalDeposit)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getDepositByTxID = `-- name: GetDepositByTxID :one
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE tx_id = $1 LIMIT 1
`

func (q *Queries) GetDepositByTxID(ctx context.Context, txID string) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByTxID, txID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Address,
		&i.UserID,
		&i.Amount,
		&i.Height,
		&i.Confirmed,
		&i.Chain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLast24hWithdrawalByUserAndChain = `-- name: GetLast24hWithdrawalByUserAndChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM withdrawals
WHERE user_id = $1
  AND chain = $2
  AND status = 'completed'
  AND created_at > NOW() - INTERVAL '24 hours'
`

type GetLast24hWithdrawalByUserAndChainParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Chain  string `db:"chain" json:"chain"`
}

func (q *Queries) GetLast24hWithdrawalByUserAndChain(ctx context.Context, arg GetLast24hWithdrawalByUserAndChainParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLast24hWithdrawalByUserAndChain, arg.UserID, arg.Chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, expires_at, revoked, created_at FROM refresh_tokens
WHERE token = $1 AND revoked = FALSE AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at FROM roles WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.name, p.description, p.created_at FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID int64) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalDepositByChain = `-- name: GetTotalDepositByChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM deposits
WHERE chain = $1 AND confirmed = 1
`

func (q *Queries) GetTotalDepositByChain(ctx context.Context, chain string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalDepositByChain, chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalDepositByUserIDAndChain = `-- name: GetTotalDepositByUserIDAndChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM deposits
WHERE user_id = $1 AND chain = $2 AND confirmed = 1
`

type GetTotalDepositByUserIDAndChainParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Chain  string `db:"chain" json:"chain"`
}

func (q *Queries) GetTotalDepositByUserIDAndChain(ctx context.Context, arg GetTotalDepositByUserIDAndChainParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalDepositByUserIDAndChain, arg.UserID, arg.Chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalWithdrawalByUserIDAndChain = `-- name: GetTotalWithdrawalByUserIDAndChain :one
SELECT COALESCE(SUM(amount), 0) as total
FROM withdrawals
WHERE user_id = $1 AND chain = $2 AND status = 'completed'
`

type GetTotalWithdrawalByUserIDAndChainParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Chain  string `db:"chain" json:"chain"`
}

func (q *Queries) GetTotalWithdrawalByUserIDAndChain(ctx context.Context, arg GetTotalWithdrawalByUserIDAndChainParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalWithdrawalByUserIDAndChain, arg.UserID, arg.Chain)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, level, username, password, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, level, username, password, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLevel = `-- name: GetUserLevel :one
SELECT level FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserLevel(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserLevel, id)
	var level int32
	err := row.Scan(&level)
	return level, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.name FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.created_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWithdrawalLimit = `-- name: GetWithdrawalLimit :one
SELECT id, level, level_name, btc_daily, eth_daily, min_deposit, created_at FROM withdrawal_limits WHERE level = $1 LIMIT 1
`

func (q *Queries) GetWithdrawalLimit(ctx context.Context, level int32) (WithdrawalLimit, error) {
	row := q.db.QueryRowContext(ctx, getWithdrawalLimit, level)
	var i WithdrawalLimit
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.LevelName,
		&i.BtcDaily,
		&i.EthDaily,
		&i.MinDeposit,
		&i.CreatedAt,
	)
	return i, err
}

const listAddressesByUserID = `-- name: ListAddressesByUserID :many
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAddressesByUserID(ctx context.Context, userID string) ([]DepositAddress, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Chain,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDepositAddresses = `-- name: ListAllDepositAddresses :many
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses ORDER BY created_at ASC
`

func (q *Queries) ListAllDepositAddresses(ctx context.Context) ([]DepositAddress, error) {
	rows, err := q.db.QueryContext(ctx, listAllDepositAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Chain,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByChain = `-- name: ListDepositsByChain :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE chain = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByChain(ctx context.Context, chain string) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDepositsByChain, chain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByUserID = `-- name: ListDepositsByUserID :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByUserID(ctx context.Context, userID string) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDepositsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedDeposits = `-- name: ListUnconfirmedDeposits :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits
WHERE confirmed = 0
ORDER BY height ASC
`

func (q *Queries) ListUnconfirmedDeposits(ctx context.Context) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listUnconfirmedDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedDeadLetters = `-- name: ListUnresolvedDeadLetters :many
SELECT id, type, payload, error, retries, resolved, created_at, updated_at FROM dead_letters
WHERE resolved = FALSE
ORDER BY created_at ASC
`

func (q *Queries) ListUnresolvedDeadLetters(ctx context.Context) ([]DeadLetter, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedDeadLetters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeadLetter
	for rows.Next() {
		var i DeadLetter
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Error,
			&i.Retries,
			&i.Resolved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, level, username, created_at, updated_at FROM users ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        int64        `db:"id" json:"id"`
	Level     int32        `db:"level" json:"level"`
	Username  string       `db:"username" json:"username"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalLimits = `-- name: ListWithdrawalLimits :many
SELECT id, level, level_name, btc_daily, eth_daily, min_deposit, created_at FROM withdrawal_limits ORDER BY level ASC
`

func (q *Queries) ListWithdrawalLimits(ctx context.Context) ([]WithdrawalLimit, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawalLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WithdrawalLimit
	for rows.Next() {
		var i WithdrawalLimit
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.LevelName,
			&i.BtcDaily,
			&i.EthDaily,
			&i.MinDeposit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByUserID = `-- name: ListWithdrawalsByUserID :many
SELECT id, tx_id, address, user_id, amount, fee, status, chain, created_at, updated_at FROM withdrawals WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWithdrawalsByUserID(ctx context.Context, userID string) ([]Withdrawal, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Fee,
			&i.Status,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	RoleID int64 `db:"role_id" json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const resolveDeadLetter = `-- name: ResolveDeadLetter :exec
UPDATE dead_letters
SET resolved = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResolveDeadLetter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resolveDeadLetter, id)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}

const updateDepositConfirmed = `-- name: UpdateDepositConfirmed :exec
UPDATE deposits
SET confirmed = 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDepositConfirmed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDepositConfirmed, id)
	return err
}

const updateUserLevel = `-- name: UpdateUserLevel :exec
UPDATE users SET level = $1 WHERE id = $2
`

type UpdateUserLevelParams struct {
	Level int32 `db:"level" json:"level"`
	ID    int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateUserLevel(ctx context.Context, arg UpdateUserLevelParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLevel, arg.Level, arg.ID)
	return err
}

const updateWithdrawalLimit = `-- name: UpdateWithdrawalLimit :exec
UPDATE withdrawal_limits
SET btc_daily = $1, eth_daily = $2
WHERE level = $3
`

type UpdateWithdrawalLimitParams struct {
	BtcDaily string `db:"btc_daily" json:"btc_daily"`
	EthDaily string `db:"eth_daily" json:"eth_daily"`
	Level    int32  `db:"level" json:"level"`
}

func (q *Queries) UpdateWithdrawalLimit(ctx context.Context, arg UpdateWithdrawalLimitParams) error {
	_, err := q.db.ExecContext(ctx, updateWithdrawalLimit, arg.BtcDaily, arg.EthDaily, arg.Level)
	return err
}

const updateWithdrawalTx = `-- name: UpdateWithdrawalTx :exec
UPDATE withdrawals
SET tx_id = $1, fee = $2, status = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateWithdrawalTxParams struct {
	TxID   sql.NullString `db:"tx_id" json:"tx_id"`
	Fee    string         `db:"fee" json:"fee"`
	Status string         `db:"status" json:"status"`
	ID     int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateWithdrawalTx(ctx context.Context, arg UpdateWithdrawalTxParams) error {
	_, err := q.db.ExecContext(ctx, updateWithdrawalTx,
		arg.TxID,
		arg.Fee,
		arg.Status,
		arg.ID,
	)
	return err
}
