// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDeposit(ctx context.Context, arg CreateDepositParams) error
	CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) error
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	GetAddressByAddress(ctx context.Context, address string) (DepositAddress, error)
	GetAllChainsTotalDeposit(ctx context.Context) (interface{}, error)
	GetDepositByTxID(ctx context.Context, txID string) (Deposit, error)
	GetTotalDepositByChain(ctx context.Context, chain string) (interface{}, error)
	GetTotalDepositByUserIDAndChain(ctx context.Context, arg GetTotalDepositByUserIDAndChainParams) (interface{}, error)
	ListAddressesByUserID(ctx context.Context, userID string) ([]DepositAddress, error)
	ListAllDepositAddresses(ctx context.Context) ([]DepositAddress, error)
	ListDepositsByChain(ctx context.Context, chain string) ([]Deposit, error)
	ListDepositsByUserID(ctx context.Context, userID string) ([]Deposit, error)
	ListUnconfirmedDeposits(ctx context.Context) ([]Deposit, error)
	ListWithdrawalsByUserID(ctx context.Context, userID string) ([]Withdrawal, error)
	UpdateWithdrawalTx(ctx context.Context, arg UpdateWithdrawalTxParams) error
}

var _ Querier = (*Queries)(nil)
