apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sweep
  namespace: {{ .Release.Namespace }}
  labels:
    app: blitz-sweep
    kubepivot.io/name: {{ .Chart.Name }}
    kubepivot.io/instance: {{ .Release.Name }}
